services:
  - type: web
    name: quera
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: tech32026@gmail.com
      - key: ADMIN_USERNAME
        value: Tech_CODERZ
      - key: ADMIN_PASSWORD
        value: ssp@2026
      - key: MAX_UPLOAD_MB
        value: "50"
